import sqlmodel

"""add song artist field

Revision ID: 70aef34eaee0
Revises: 91f7f4ad4e11
Create Date: 2025-09-09 10:28:10.762897+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aef34eaee0'
down_revision: Union[str, Sequence[str], None] = '91f7f4ad4e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'artist')
    # ### end Alembic commands ###
