import sqlmodel

"""allow null song language

Revision ID: 4b4574933f90
Revises: c62d711d7c7a
Create Date: 2025-09-09 03:58:05.484596+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b4574933f90'
down_revision: Union[str, Sequence[str], None] = 'c62d711d7c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'language',
               existing_type=postgresql.ENUM('SPANISH', 'ENGLISH', 'YORUBA', 'IGBO', 'HAUSA', 'PIDGIN_ENGLISH', name='songlanguage'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'language',
               existing_type=postgresql.ENUM('SPANISH', 'ENGLISH', 'YORUBA', 'IGBO', 'HAUSA', 'PIDGIN_ENGLISH', name='songlanguage'),
               nullable=False)
    # ### end Alembic commands ###
