import sqlmodel

"""allow null primary keys

Revision ID: 91f7f4ad4e11
Revises: 4b4574933f90
Create Date: 2025-09-09 04:14:51.221743+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f7f4ad4e11'
down_revision: Union[str, Sequence[str], None] = '4b4574933f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
